/**
 * Mathematics skill tree — grades 1-4 (ФГОС НОО РФ).
 * Flat list ordered by curriculum sequence.
 */

import type { SkillNode } from "./fgos-tree";

export const MATH_SKILLS: SkillNode[] = [
  // ══ 1 класс ══
  {
    id: "math_count10",
    name: "Счёт до 10",
    subject: "math",
    icon: "🔢",
    color: "#3B82F6",
    generatorId: "add",
    grade: 1,
    progressToComplete: 100,
    unlocks: ["math_add10"],
    gatesChapterIds: [],
  },
  {
    id: "math_add10",
    name: "Сложение в пределах 10",
    subject: "math",
    icon: "➕",
    color: "#3B82F6",
    generatorId: "add",
    grade: 1,
    progressToComplete: 100,
    unlocks: ["math_sub10"],
    gatesChapterIds: [],
  },
  {
    id: "math_sub10",
    name: "Вычитание в пределах 10",
    subject: "math",
    icon: "➖",
    color: "#EF4444",
    generatorId: "sub",
    grade: 1,
    progressToComplete: 100,
    unlocks: ["math_add20"],
    gatesChapterIds: [],
  },
  {
    id: "math_add20",
    name: "Сложение до 20",
    subject: "math",
    icon: "➕",
    color: "#3B82F6",
    generatorId: "add",
    grade: 1,
    progressToComplete: 100,
    unlocks: ["math_sub20"],
    gatesChapterIds: [],
  },
  {
    id: "math_sub20",
    name: "Вычитание до 20",
    subject: "math",
    icon: "➖",
    color: "#EF4444",
    generatorId: "sub",
    grade: 1,
    progressToComplete: 100,
    unlocks: ["math_compare"],
    gatesChapterIds: ["math1"],
  },
  {
    id: "math_compare",
    name: "Сравнение чисел",
    subject: "math",
    icon: "⚖️",
    color: "#F59E0B",
    generatorId: "compare",
    grade: 1,
    progressToComplete: 100,
    unlocks: ["math_text10"],
    gatesChapterIds: [],
  },
  {
    id: "math_text10",
    name: "Текстовые задачи (до 10)",
    subject: "math",
    icon: "📝",
    color: "#8B5CF6",
    generatorId: "word",
    grade: 1,
    progressToComplete: 100,
    unlocks: ["math_money"],
    gatesChapterIds: [],
  },
  {
    id: "math_money",
    name: "Деньги и покупки",
    subject: "math",
    icon: "💰",
    color: "#F59E0B",
    generatorId: "money",
    grade: 1,
    progressToComplete: 100,
    unlocks: [],
    gatesChapterIds: ["math1"],
  },

  // ══ 2 класс ══
  {
    id: "math_add100",
    name: "Сложение в пределах 100",
    subject: "math",
    icon: "➕",
    color: "#3B82F6",
    generatorId: "add",
    grade: 2,
    progressToComplete: 100,
    unlocks: ["math_sub100"],
    gatesChapterIds: [],
  },
  {
    id: "math_sub100",
    name: "Вычитание в пределах 100",
    subject: "math",
    icon: "➖",
    color: "#EF4444",
    generatorId: "sub",
    grade: 2,
    progressToComplete: 100,
    unlocks: ["math_time"],
    gatesChapterIds: [],
  },
  {
    id: "math_time",
    name: "Часы и календарь",
    subject: "math",
    icon: "⏱️",
    color: "#14B8A6",
    generatorId: "time",
    grade: 2,
    progressToComplete: 100,
    unlocks: ["math_units"],
    gatesChapterIds: [],
  },
  {
    id: "math_units",
    name: "Единицы измерения",
    subject: "math",
    icon: "📏",
    color: "#6366F1",
    generatorId: "units",
    grade: 2,
    progressToComplete: 100,
    unlocks: ["math_mul_intro"],
    gatesChapterIds: [],
  },
  {
    id: "math_mul_intro",
    name: "Умножение: что это?",
    subject: "math",
    icon: "✖️",
    color: "#F59E0B",
    generatorId: "mul",
    grade: 2,
    progressToComplete: 100,
    unlocks: ["math_mul_table"],
    gatesChapterIds: [],
  },
  {
    id: "math_mul_table",
    name: "Таблица умножения до 5",
    subject: "math",
    icon: "📊",
    color: "#F97316",
    generatorId: "mul",
    grade: 2,
    progressToComplete: 100,
    unlocks: ["math_div_intro"],
    gatesChapterIds: [],
  },
  {
    id: "math_div_intro",
    name: "Деление: что это?",
    subject: "math",
    icon: "➗",
    color: "#8B5CF6",
    generatorId: "div",
    grade: 2,
    progressToComplete: 100,
    unlocks: ["math_eq_easy"],
    gatesChapterIds: [],
  },
  {
    id: "math_eq_easy",
    name: "Простые уравнения",
    subject: "math",
    icon: "🔎",
    color: "#EC4899",
    generatorId: "eq",
    grade: 2,
    progressToComplete: 100,
    unlocks: [],
    gatesChapterIds: ["math2"],
  },

  // ══ 3 класс ══
  {
    id: "math_mul_full",
    name: "Таблица умножения до 9",
    subject: "math",
    icon: "📊",
    color: "#F97316",
    generatorId: "mul",
    grade: 3,
    progressToComplete: 100,
    unlocks: ["math_div_table"],
    gatesChapterIds: [],
  },
  {
    id: "math_div_table",
    name: "Деление по таблице",
    subject: "math",
    icon: "➗",
    color: "#8B5CF6",
    generatorId: "div",
    grade: 3,
    progressToComplete: 100,
    unlocks: ["math_div_rem"],
    gatesChapterIds: [],
  },
  {
    id: "math_div_rem",
    name: "Деление с остатком",
    subject: "math",
    icon: "🧮",
    color: "#14B8A6",
    generatorId: "div",
    grade: 3,
    progressToComplete: 100,
    unlocks: ["math_equations"],
    gatesChapterIds: [],
  },
  {
    id: "math_equations",
    name: "Уравнения и неравенства",
    subject: "math",
    icon: "🔎",
    color: "#EC4899",
    generatorId: "eq",
    grade: 3,
    progressToComplete: 100,
    unlocks: ["math_perimeter"],
    gatesChapterIds: [],
  },
  {
    id: "math_perimeter",
    name: "Периметр фигур",
    subject: "math",
    icon: "📏",
    color: "#14B8A6",
    generatorId: "geom",
    grade: 3,
    progressToComplete: 100,
    unlocks: ["math_area"],
    gatesChapterIds: [],
  },
  {
    id: "math_area",
    name: "Площадь прямоугольника",
    subject: "math",
    icon: "📐",
    color: "#10B981",
    generatorId: "geom",
    grade: 3,
    progressToComplete: 100,
    unlocks: ["math_logic"],
    gatesChapterIds: [],
  },
  {
    id: "math_logic",
    name: "Логические задачи",
    subject: "math",
    icon: "🧩",
    color: "#EC4899",
    generatorId: "logic",
    grade: 3,
    progressToComplete: 100,
    unlocks: [],
    gatesChapterIds: ["math3"],
  },

  // ══ 4 класс ══
  {
    id: "math_multidigit",
    name: "Многозначные числа",
    subject: "math",
    icon: "🔢",
    color: "#3B82F6",
    generatorId: "add",
    grade: 4,
    progressToComplete: 100,
    unlocks: ["math_column_add"],
    gatesChapterIds: [],
  },
  {
    id: "math_column_add",
    name: "Сложение столбиком",
    subject: "math",
    icon: "📋",
    color: "#3B82F6",
    generatorId: "add",
    grade: 4,
    progressToComplete: 100,
    unlocks: ["math_column_mul"],
    gatesChapterIds: [],
  },
  {
    id: "math_column_mul",
    name: "Умножение столбиком",
    subject: "math",
    icon: "📋",
    color: "#F59E0B",
    generatorId: "mul",
    grade: 4,
    progressToComplete: 100,
    unlocks: ["math_column_div"],
    gatesChapterIds: [],
  },
  {
    id: "math_column_div",
    name: "Деление уголком",
    subject: "math",
    icon: "📋",
    color: "#8B5CF6",
    generatorId: "div",
    grade: 4,
    progressToComplete: 100,
    unlocks: ["math_fractions"],
    gatesChapterIds: [],
  },
  {
    id: "math_fractions",
    name: "Дроби и доли",
    subject: "math",
    icon: "🍕",
    color: "#F97316",
    generatorId: "frac",
    grade: 4,
    progressToComplete: 100,
    unlocks: ["math_geom_adv"],
    gatesChapterIds: [],
  },
  {
    id: "math_geom_adv",
    name: "Геометрия: фигуры и объём",
    subject: "math",
    icon: "📐",
    color: "#14B8A6",
    generatorId: "geom",
    grade: 4,
    progressToComplete: 100,
    unlocks: ["math_speed"],
    gatesChapterIds: [],
  },
  {
    id: "math_speed",
    name: "Скорость, время, расстояние",
    subject: "math",
    icon: "⚡",
    color: "#F59E0B",
    generatorId: "speed",
    grade: 4,
    progressToComplete: 100,
    unlocks: ["math_charts"],
    gatesChapterIds: [],
  },
  {
    id: "math_charts",
    name: "Диаграммы и таблицы",
    subject: "math",
    icon: "📊",
    color: "#06B6D4",
    generatorId: "charts",
    grade: 4,
    progressToComplete: 100,
    unlocks: [],
    gatesChapterIds: ["math4", "math5"],
  },
];

/** All unlocked math generators */
export const MATH_GENERATOR_IDS = [
  "add", "sub", "compare", "word",
  "mul", "div",
  "eq", "geom", "frac",
  "time", "units", "money", "logic",
  "speed", "charts",
] as const;
