import type { FGOSCurriculum } from "./fgos-tree";

/**
 * FGOS Mathematics curriculum — grades 1-4 (ФГОС НОО РФ).
 * Each topic maps to a generatorId matching existing task generators.
 */

export const MATH_CURRICULUM: FGOSCurriculum = {
  subject: "math",
  grades: [
    {
      grade: 1,
      label: "1 класс",
      quarters: [
        {
          quarter: 1,
          label: "I четверть",
          topics: [
            {
              id: "math_1_1_count",
              name: "Числа от 1 до 10. Счёт",
              subject: "math",
              icon: "🔢",
              color: "#3B82F6",
              generatorId: "add",
              progressToComplete: 100,
              prerequisites: [],
              gatesChapterIds: [],
              obstacleType: "choice",
              obstacleDifficulty: 1,
              olympiadVariantId: null,
            },
          ],
        },
        {
          quarter: 2,
          label: "II четверть",
          topics: [
            {
              id: "math_1_2_add_sub",
              name: "Сложение и вычитание в пределах 10",
              subject: "math",
              icon: "➕",
              color: "#3B82F6",
              generatorId: "add",
              progressToComplete: 100,
              prerequisites: ["math_1_1_count"],
              gatesChapterIds: [],
              obstacleType: "choice",
              obstacleDifficulty: 1,
              olympiadVariantId: null,
            },
          ],
        },
        {
          quarter: 3,
          label: "III четверть",
          topics: [
            {
              id: "math_1_3_add_sub_20",
              name: "Сложение и вычитание в пределах 20",
              subject: "math",
              icon: "➖",
              color: "#EF4444",
              generatorId: "sub",
              progressToComplete: 100,
              prerequisites: ["math_1_2_add_sub"],
              gatesChapterIds: [],
              obstacleType: "input",
              obstacleDifficulty: 1,
              olympiadVariantId: null,
            },
          ],
        },
        {
          quarter: 4,
          label: "IV четверть",
          topics: [
            {
              id: "math_1_4_review",
              name: "Повторение. Текстовые задачи",
              subject: "math",
              icon: "📝",
              color: "#8B5CF6",
              generatorId: "add",
              progressToComplete: 100,
              prerequisites: ["math_1_3_add_sub_20"],
              gatesChapterIds: ["math"],
              obstacleType: "pair",
              obstacleDifficulty: 2,
              olympiadVariantId: null,
            },
          ],
        },
      ],
    },
    {
      grade: 2,
      label: "2 класс",
      quarters: [
        {
          quarter: 1,
          label: "I четверть",
          topics: [
            {
              id: "math_2_1_add_100",
              name: "Сложение и вычитание в пределах 100",
              subject: "math",
              icon: "➕",
              color: "#3B82F6",
              generatorId: "add",
              progressToComplete: 100,
              prerequisites: ["math_1_4_review"],
              gatesChapterIds: [],
              obstacleType: "choice",
              obstacleDifficulty: 2,
              olympiadVariantId: null,
            },
          ],
        },
        {
          quarter: 2,
          label: "II четверть",
          topics: [
            {
              id: "math_2_2_mul_intro",
              name: "Умножение (введение)",
              subject: "math",
              icon: "✖️",
              color: "#F59E0B",
              generatorId: "mul",
              progressToComplete: 100,
              prerequisites: ["math_2_1_add_100"],
              gatesChapterIds: [],
              obstacleType: "choice",
              obstacleDifficulty: 2,
              olympiadVariantId: null,
            },
          ],
        },
        {
          quarter: 3,
          label: "III четверть",
          topics: [
            {
              id: "math_2_3_mul_div",
              name: "Умножение и деление",
              subject: "math",
              icon: "➗",
              color: "#8B5CF6",
              generatorId: "div",
              progressToComplete: 100,
              prerequisites: ["math_2_2_mul_intro"],
              gatesChapterIds: [],
              obstacleType: "input",
              obstacleDifficulty: 2,
              olympiadVariantId: null,
            },
          ],
        },
        {
          quarter: 4,
          label: "IV четверть",
          topics: [
            {
              id: "math_2_4_eq_intro",
              name: "Уравнения (введение)",
              subject: "math",
              icon: "🔎",
              color: "#EC4899",
              generatorId: "eq",
              progressToComplete: 100,
              prerequisites: ["math_2_3_mul_div"],
              gatesChapterIds: ["math2"],
              obstacleType: "pair",
              obstacleDifficulty: 2,
              olympiadVariantId: "math_olymp_eq",
            },
          ],
        },
      ],
    },
    {
      grade: 3,
      label: "3 класс",
      quarters: [
        {
          quarter: 1,
          label: "I четверть",
          topics: [
            {
              id: "math_3_1_mul_table",
              name: "Таблица умножения",
              subject: "math",
              icon: "✖️",
              color: "#F59E0B",
              generatorId: "mul",
              progressToComplete: 100,
              prerequisites: ["math_2_4_eq_intro"],
              gatesChapterIds: [],
              obstacleType: "choice",
              obstacleDifficulty: 3,
              olympiadVariantId: "math_olymp_mul",
            },
          ],
        },
        {
          quarter: 2,
          label: "II четверть",
          topics: [
            {
              id: "math_3_2_division",
              name: "Деление в пределах 100",
              subject: "math",
              icon: "➗",
              color: "#8B5CF6",
              generatorId: "div",
              progressToComplete: 100,
              prerequisites: ["math_3_1_mul_table"],
              gatesChapterIds: [],
              obstacleType: "input",
              obstacleDifficulty: 3,
              olympiadVariantId: null,
            },
          ],
        },
        {
          quarter: 3,
          label: "III четверть",
          topics: [
            {
              id: "math_3_3_equations",
              name: "Уравнения и выражения",
              subject: "math",
              icon: "🔎",
              color: "#EC4899",
              generatorId: "eq",
              progressToComplete: 100,
              prerequisites: ["math_3_2_division"],
              gatesChapterIds: [],
              obstacleType: "boss",
              obstacleDifficulty: 3,
              olympiadVariantId: "math_olymp_eq",
            },
          ],
        },
        {
          quarter: 4,
          label: "IV четверть",
          topics: [
            {
              id: "math_3_4_geometry_intro",
              name: "Геометрические фигуры. Периметр",
              subject: "math",
              icon: "📏",
              color: "#14B8A6",
              generatorId: "geom",
              progressToComplete: 100,
              prerequisites: ["math_3_3_equations"],
              gatesChapterIds: ["math3"],
              obstacleType: "pair",
              obstacleDifficulty: 2,
              olympiadVariantId: null,
            },
          ],
        },
      ],
    },
    {
      grade: 4,
      label: "4 класс",
      quarters: [
        {
          quarter: 1,
          label: "I четверть",
          topics: [
            {
              id: "math_4_1_eq_advanced",
              name: "Уравнения (углубление)",
              subject: "math",
              icon: "🔎",
              color: "#EC4899",
              generatorId: "eq",
              progressToComplete: 100,
              prerequisites: ["math_3_4_geometry_intro"],
              gatesChapterIds: [],
              obstacleType: "boss",
              obstacleDifficulty: 3,
              olympiadVariantId: "math_olymp_eq",
            },
          ],
        },
        {
          quarter: 2,
          label: "II четверть",
          topics: [
            {
              id: "math_4_2_geometry",
              name: "Периметр и площадь",
              subject: "math",
              icon: "📏",
              color: "#14B8A6",
              generatorId: "geom",
              progressToComplete: 100,
              prerequisites: ["math_4_1_eq_advanced"],
              gatesChapterIds: [],
              obstacleType: "pair",
              obstacleDifficulty: 3,
              olympiadVariantId: null,
            },
          ],
        },
        {
          quarter: 3,
          label: "III четверть",
          topics: [
            {
              id: "math_4_3_fractions",
              name: "Дроби",
              subject: "math",
              icon: "🍕",
              color: "#F97316",
              generatorId: "frac",
              progressToComplete: 100,
              prerequisites: ["math_4_2_geometry"],
              gatesChapterIds: ["math4"],
              obstacleType: "choice",
              obstacleDifficulty: 3,
              olympiadVariantId: "math_olymp_frac",
            },
          ],
        },
        {
          quarter: 4,
          label: "IV четверть",
          topics: [
            {
              id: "math_4_4_review",
              name: "Итоговое повторение",
              subject: "math",
              icon: "🏆",
              color: "#F59E0B",
              generatorId: "add",
              progressToComplete: 100,
              prerequisites: ["math_4_3_fractions"],
              gatesChapterIds: ["math5"],
              obstacleType: "boss",
              obstacleDifficulty: 3,
              olympiadVariantId: null,
            },
          ],
        },
      ],
    },
  ],
};
