import type { FGOSCurriculum } from "./fgos-tree";

/**
 * FGOS Russian Language curriculum — grades 1-4 (ФГОС НОО РФ).
 */

export const RUSSIAN_CURRICULUM: FGOSCurriculum = {
  subject: "russian",
  grades: [
    {
      grade: 1,
      label: "1 класс",
      quarters: [
        {
          quarter: 1,
          label: "I четверть",
          topics: [
            {
              id: "rus_1_1_abc",
              name: "Алфавит. Звуки и буквы",
              subject: "russian",
              icon: "🔤",
              color: "#7C3AED",
              generatorId: "zhishi",
              progressToComplete: 100,
              prerequisites: [],
              gatesChapterIds: [],
              obstacleType: "choice",
              obstacleDifficulty: 1,
              olympiadVariantId: null,
            },
          ],
        },
        {
          quarter: 2,
          label: "II четверть",
          topics: [
            {
              id: "rus_1_2_zhishi",
              name: "Правописание ЖИ/ШИ, ЧА/ЩА, ЧУ/ЩУ",
              subject: "russian",
              icon: "✍️",
              color: "#7C3AED",
              generatorId: "zhishi",
              progressToComplete: 100,
              prerequisites: ["rus_1_1_abc"],
              gatesChapterIds: [],
              obstacleType: "choice",
              obstacleDifficulty: 1,
              olympiadVariantId: null,
            },
          ],
        },
        {
          quarter: 3,
          label: "III четверть",
          topics: [
            {
              id: "rus_1_3_soft",
              name: "Мягкий знак (Ь)",
              subject: "russian",
              icon: "🧩",
              color: "#8B5CF6",
              generatorId: "soft",
              progressToComplete: 100,
              prerequisites: ["rus_1_2_zhishi"],
              gatesChapterIds: [],
              obstacleType: "choice",
              obstacleDifficulty: 1,
              olympiadVariantId: null,
            },
          ],
        },
        {
          quarter: 4,
          label: "IV четверть",
          topics: [
            {
              id: "rus_1_4_review",
              name: "Повторение правил письма",
              subject: "russian",
              icon: "📝",
              color: "#14B8A6",
              generatorId: "zhishi",
              progressToComplete: 100,
              prerequisites: ["rus_1_3_soft"],
              gatesChapterIds: [],
              obstacleType: "pair",
              obstacleDifficulty: 2,
              olympiadVariantId: null,
            },
          ],
        },
      ],
    },
    {
      grade: 2,
      label: "2 класс",
      quarters: [
        {
          quarter: 1,
          label: "I четверть",
          topics: [
            {
              id: "rus_2_1_vowel",
              name: "Безударные гласные в корне",
              subject: "russian",
              icon: "🔎",
              color: "#F59E0B",
              generatorId: "vowel",
              progressToComplete: 100,
              prerequisites: ["rus_1_4_review"],
              gatesChapterIds: [],
              obstacleType: "input",
              obstacleDifficulty: 2,
              olympiadVariantId: null,
            },
          ],
        },
        {
          quarter: 2,
          label: "II четверть",
          topics: [
            {
              id: "rus_2_2_silent",
              name: "Непроизносимые согласные",
              subject: "russian",
              icon: "🗣️",
              color: "#EC4899",
              generatorId: "silent",
              progressToComplete: 100,
              prerequisites: ["rus_2_1_vowel"],
              gatesChapterIds: [],
              obstacleType: "choice",
              obstacleDifficulty: 2,
              olympiadVariantId: null,
            },
          ],
        },
        {
          quarter: 3,
          label: "III четверть",
          topics: [
            {
              id: "rus_2_3_hard_sign",
              name: "Разделительный Ъ",
              subject: "russian",
              icon: "🧩",
              color: "#8B5CF6",
              generatorId: "soft",
              progressToComplete: 100,
              prerequisites: ["rus_2_2_silent"],
              gatesChapterIds: [],
              obstacleType: "choice",
              obstacleDifficulty: 2,
              olympiadVariantId: null,
            },
          ],
        },
        {
          quarter: 4,
          label: "IV четверть",
          topics: [
            {
              id: "rus_2_4_tsya_intro",
              name: "-ТСЯ и -ТЬСЯ в глаголах",
              subject: "russian",
              icon: "🔄",
              color: "#14B8A6",
              generatorId: "tsya",
              progressToComplete: 100,
              prerequisites: ["rus_2_3_hard_sign"],
              gatesChapterIds: ["rus1"],
              obstacleType: "input",
              obstacleDifficulty: 2,
              olympiadVariantId: null,
            },
          ],
        },
      ],
    },
    {
      grade: 3,
      label: "3 класс",
      quarters: [
        {
          quarter: 1,
          label: "I четверть",
          topics: [
            {
              id: "rus_3_1_vowel_deep",
              name: "Безударные гласные (углубление)",
              subject: "russian",
              icon: "🔎",
              color: "#F59E0B",
              generatorId: "vowel",
              progressToComplete: 100,
              prerequisites: ["rus_2_4_tsya_intro"],
              gatesChapterIds: [],
              obstacleType: "input",
              obstacleDifficulty: 3,
              olympiadVariantId: "rus_olymp_vowel",
            },
          ],
        },
        {
          quarter: 2,
          label: "II четверть",
          topics: [
            {
              id: "rus_3_2_tsya",
              name: "-ТСЯ/-ТЬСЯ (закрепление)",
              subject: "russian",
              icon: "🔄",
              color: "#14B8A6",
              generatorId: "tsya",
              progressToComplete: 100,
              prerequisites: ["rus_3_1_vowel_deep"],
              gatesChapterIds: [],
              obstacleType: "choice",
              obstacleDifficulty: 3,
              olympiadVariantId: null,
            },
          ],
        },
        {
          quarter: 3,
          label: "III четверть",
          topics: [
            {
              id: "rus_3_3_nn_intro",
              name: "Н и НН в суффиксах",
              subject: "russian",
              icon: "📋",
              color: "#EF4444",
              generatorId: "nn",
              progressToComplete: 100,
              prerequisites: ["rus_3_2_tsya"],
              gatesChapterIds: [],
              obstacleType: "boss",
              obstacleDifficulty: 3,
              olympiadVariantId: null,
            },
          ],
        },
        {
          quarter: 4,
          label: "IV четверть",
          topics: [
            {
              id: "rus_3_4_review",
              name: "Орфографический практикум",
              subject: "russian",
              icon: "📝",
              color: "#F97316",
              generatorId: "zhishi",
              progressToComplete: 100,
              prerequisites: ["rus_3_3_nn_intro"],
              gatesChapterIds: ["rus2"],
              obstacleType: "pair",
              obstacleDifficulty: 2,
              olympiadVariantId: null,
            },
          ],
        },
      ],
    },
    {
      grade: 4,
      label: "4 класс",
      quarters: [
        {
          quarter: 1,
          label: "I четверть",
          topics: [
            {
              id: "rus_4_1_prepri",
              name: "Правописание ПРЕ/ПРИ",
              subject: "russian",
              icon: "🎯",
              color: "#F97316",
              generatorId: "prepri",
              progressToComplete: 100,
              prerequisites: ["rus_3_4_review"],
              gatesChapterIds: [],
              obstacleType: "choice",
              obstacleDifficulty: 3,
              olympiadVariantId: "rus_olymp_prepri",
            },
          ],
        },
        {
          quarter: 2,
          label: "II четверть",
          topics: [
            {
              id: "rus_4_2_nn_deep",
              name: "Н и НН (углубление)",
              subject: "russian",
              icon: "📋",
              color: "#EF4444",
              generatorId: "nn",
              progressToComplete: 100,
              prerequisites: ["rus_4_1_prepri"],
              gatesChapterIds: [],
              obstacleType: "boss",
              obstacleDifficulty: 3,
              olympiadVariantId: "rus_olymp_nn",
            },
          ],
        },
        {
          quarter: 3,
          label: "III четверть",
          topics: [
            {
              id: "rus_4_3_silent_deep",
              name: "Непроизносимые согласные (закрепление)",
              subject: "russian",
              icon: "🗣️",
              color: "#EC4899",
              generatorId: "silent",
              progressToComplete: 100,
              prerequisites: ["rus_4_2_nn_deep"],
              gatesChapterIds: ["rus3"],
              obstacleType: "input",
              obstacleDifficulty: 3,
              olympiadVariantId: null,
            },
          ],
        },
        {
          quarter: 4,
          label: "IV четверть",
          topics: [
            {
              id: "rus_4_4_exam",
              name: "Итоговый диктант",
              subject: "russian",
              icon: "🏆",
              color: "#7C3AED",
              generatorId: "zhishi",
              progressToComplete: 100,
              prerequisites: ["rus_4_3_silent_deep"],
              gatesChapterIds: ["rus4", "rus5"],
              obstacleType: "boss",
              obstacleDifficulty: 3,
              olympiadVariantId: null,
            },
          ],
        },
      ],
    },
  ],
};
