/**
 * Russian language skill tree — grades 1-4 (ФГОС НОО РФ).
 */

import type { SkillNode } from "./fgos-tree";

export const RUSSIAN_SKILLS: SkillNode[] = [
  // ══ 1 класс ══
  {
    id: "rus_alphabet",
    name: "Алфавит. Звуки и буквы",
    subject: "russian",
    icon: "🔤",
    color: "#7C3AED",
    generatorId: "alphabet",
    grade: 1,
    progressToComplete: 100,
    unlocks: ["rus_syllables"],
    gatesChapterIds: [],
  },
  {
    id: "rus_syllables",
    name: "Слоги и ударение",
    subject: "russian",
    icon: "🎵",
    color: "#A855F7",
    generatorId: "alphabet",
    grade: 1,
    progressToComplete: 100,
    unlocks: ["rus_zhishi"],
    gatesChapterIds: [],
  },
  {
    id: "rus_zhishi",
    name: "ЖИ/ШИ, ЧА/ЩА, ЧУ/ЩУ",
    subject: "russian",
    icon: "✍️",
    color: "#7C3AED",
    generatorId: "zhishi",
    grade: 1,
    progressToComplete: 100,
    unlocks: ["rus_soft_sign"],
    gatesChapterIds: [],
  },
  {
    id: "rus_soft_sign",
    name: "Мягкий знак (Ь)",
    subject: "russian",
    icon: "🧩",
    color: "#8B5CF6",
    generatorId: "soft",
    grade: 1,
    progressToComplete: 100,
    unlocks: ["rus_capital"],
    gatesChapterIds: [],
  },
  {
    id: "rus_capital",
    name: "Большая буква",
    subject: "russian",
    icon: "🔠",
    color: "#6366F1",
    generatorId: "capital",
    grade: 1,
    progressToComplete: 100,
    unlocks: [],
    gatesChapterIds: [],
  },

  // ══ 2 класс ══
  {
    id: "rus_vowel",
    name: "Безударные гласные",
    subject: "russian",
    icon: "🔎",
    color: "#F59E0B",
    generatorId: "vowel",
    grade: 2,
    progressToComplete: 100,
    unlocks: ["rus_consonant"],
    gatesChapterIds: [],
  },
  {
    id: "rus_consonant",
    name: "Парные согласные",
    subject: "russian",
    icon: "🔊",
    color: "#EC4899",
    generatorId: "consonant",
    grade: 2,
    progressToComplete: 100,
    unlocks: ["rus_silent"],
    gatesChapterIds: [],
  },
  {
    id: "rus_silent",
    name: "Непроизносимые согласные",
    subject: "russian",
    icon: "🗣️",
    color: "#EC4899",
    generatorId: "silent",
    grade: 2,
    progressToComplete: 100,
    unlocks: ["rus_hard_sign"],
    gatesChapterIds: [],
  },
  {
    id: "rus_hard_sign",
    name: "Разделительный Ъ",
    subject: "russian",
    icon: "🧩",
    color: "#8B5CF6",
    generatorId: "hard_sign",
    grade: 2,
    progressToComplete: 100,
    unlocks: ["rus_word_parts"],
    gatesChapterIds: [],
  },
  {
    id: "rus_word_parts",
    name: "Состав слова",
    subject: "russian",
    icon: "🧱",
    color: "#F59E0B",
    generatorId: "word_parts",
    grade: 2,
    progressToComplete: 100,
    unlocks: ["rus_punctuation"],
    gatesChapterIds: [],
  },
  {
    id: "rus_punctuation",
    name: "Знаки препинания",
    subject: "russian",
    icon: "📝",
    color: "#10B981",
    generatorId: "punct",
    grade: 2,
    progressToComplete: 100,
    unlocks: ["rus_tsya_intro"],
    gatesChapterIds: [],
  },
  {
    id: "rus_synonyms",
    name: "Синонимы и антонимы",
    subject: "russian",
    icon: "🔤",
    color: "#F97316",
    generatorId: "synonyms",
    grade: 2,
    progressToComplete: 100,
    unlocks: [],
    gatesChapterIds: ["rus1"],
  },

  // ══ 3 класс ══
  {
    id: "rus_tsya",
    name: "-ТСЯ и -ТЬСЯ в глаголах",
    subject: "russian",
    icon: "🔄",
    color: "#14B8A6",
    generatorId: "tsya",
    grade: 3,
    progressToComplete: 100,
    unlocks: ["rus_case_nouns"],
    gatesChapterIds: [],
  },
  {
    id: "rus_case_nouns",
    name: "Падежи имён сущ.",
    subject: "russian",
    icon: "📑",
    color: "#0EA5E9",
    generatorId: "cases",
    grade: 3,
    progressToComplete: 100,
    unlocks: ["rus_vowel_deep"],
    gatesChapterIds: [],
  },
  {
    id: "rus_vowel_deep",
    name: "Чередование гласных в корне",
    subject: "russian",
    icon: "🔄",
    color: "#F59E0B",
    generatorId: "vowel",
    grade: 3,
    progressToComplete: 100,
    unlocks: [],
    gatesChapterIds: ["rus2"],
  },

  // ══ 4 класс ══
  {
    id: "rus_prepri",
    name: "ПРЕ- и ПРИ-",
    subject: "russian",
    icon: "🎯",
    color: "#F97316",
    generatorId: "prepri",
    grade: 4,
    progressToComplete: 100,
    unlocks: ["rus_nn"],
    gatesChapterIds: [],
  },
  {
    id: "rus_nn",
    name: "Н и НН в суффиксах",
    subject: "russian",
    icon: "📋",
    color: "#EF4444",
    generatorId: "nn",
    grade: 4,
    progressToComplete: 100,
    unlocks: ["rus_case_adj"],
    gatesChapterIds: [],
  },
  {
    id: "rus_case_adj",
    name: "Склонение прилагательных",
    subject: "russian",
    icon: "📋",
    color: "#8B5CF6",
    generatorId: "cases",
    grade: 4,
    progressToComplete: 100,
    unlocks: ["rus_nn_deep"],
    gatesChapterIds: [],
  },
  {
    id: "rus_nn_deep",
    name: "Н/НН в причастиях",
    subject: "russian",
    icon: "📋",
    color: "#EF4444",
    generatorId: "nn",
    grade: 4,
    progressToComplete: 100,
    unlocks: ["rus_pronouns"],
    gatesChapterIds: [],
  },
  {
    id: "rus_pronouns",
    name: "Местоимения",
    subject: "russian",
    icon: "👤",
    color: "#06B6D4",
    generatorId: "pronouns",
    grade: 4,
    progressToComplete: 100,
    unlocks: ["rus_adverbs"],
    gatesChapterIds: [],
  },
  {
    id: "rus_adverbs",
    name: "Наречия",
    subject: "russian",
    icon: "🏃",
    color: "#F59E0B",
    generatorId: "verbs",
    grade: 4,
    progressToComplete: 100,
    unlocks: ["rus_verb_conj"],
    gatesChapterIds: [],
  },
  {
    id: "rus_verb_conj",
    name: "Спряжение глаголов",
    subject: "russian",
    icon: "📝",
    color: "#10B981",
    generatorId: "verbs",
    grade: 4,
    progressToComplete: 100,
    unlocks: ["rus_parts_of_speech"],
    gatesChapterIds: [],
  },
  {
    id: "rus_parts_of_speech",
    name: "Части речи и разбор",
    subject: "russian",
    icon: "🧠",
    color: "#6366F1",
    generatorId: "verbs",
    grade: 4,
    progressToComplete: 100,
    unlocks: ["rus_dictation"],
    gatesChapterIds: [],
  },
  {
    id: "rus_dictation",
    name: "Итоговый диктант",
    subject: "russian",
    icon: "🏆",
    color: "#7C3AED",
    generatorId: "zhishi",
    grade: 4,
    progressToComplete: 100,
    unlocks: [],
    gatesChapterIds: ["rus3", "rus4", "rus5"],
  },
];

/** All unlocked russian generators */
export const RUSSIAN_GENERATOR_IDS = [
  "alphabet", "zhishi", "soft", "capital",
  "vowel", "consonant", "silent", "hard_sign",
  "tsya", "nn", "cases",
  "prepri", "verbs",
  "word_parts", "punct", "synonyms", "pronouns",
] as const;
